[tool.poetry]
name = "backend-payments-python"
version = "0.1.0"
description = "Payment processing backend implemented in Python using FastAPI, SQLAlchemy, and Redis."
authors = ["LookAndCris <look.dev.aws@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "*"
uvicorn = {extras = ["standard"], version = "*"}
sqlalchemy = "*"
asyncpg = "*"
redis = "*"
python-dotenv = "^1.2.2"
pydantic-settings = "^2.13.1"
structlog = "^25.5.0"
dotenv = "^0.9.9"
python-jose = {extras = ["cryptography"], version = "^3.5.0"}
bcrypt = "4.1.2"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
slowapi = "^0.1.9"
limits = "^5.8.0"
hiredis = "^3.3.1"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-asyncio = "*"
httpx = "*"
pytest-cov = "*"
pytest-mock = "^3.15.1"
fakeredis = "^2.34.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["test"]
pythonpath = ["."]
